<!DOCTYPE html>
<html lang="en">
    <head>
        <?php include 'head.html'; ?>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.9/validator.min.js"></script>
        <style>
            form {
                margin-top: 14em;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <?php if ($error) { ?>
            <div class="alert alert-danger alert-dismissible" role="alert"">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong><?=$view->translate('Sorry!') ?> </strong><?=$error?>
            </div>
            <?php } ?>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <form method="post" data-toggle="validator" role="form">
                        <div class="form-group">
                            <label for="lang_selector"><?= $view->translate('Interface language') ?></label>
                            <select id="lang_selector" class="form-control" name="lang" onchange="selectLang(this)">
                                <?php $ifaceLang = $view->get('translator')->getLang() ?>
                                <option <?= $ifaceLang == 'en' ? 'selected' : '' ?> value="en">English (EN)</option>
                                <option <?= $ifaceLang == 'ru' ? 'selected' : '' ?> value="ru">Русский (RU)</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="email"><?= $view->translate('Email Address') ?>:</label>
                            <input
                                type="email"
                                name="email"
                                class="form-control"
                                id="email"
                                required
                                placeholder='<?= $view->translate("You email") ?>'
                                value="<?=$email?>"
                                data-type-error="<?= $view->translate('Invalid email') ?>"
                                data-required-error="<?= $view->translate('Please fill this field') ?>"
                            >
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <label for="pwd"><?= $view->translate('Password') ?>:</label>
                            <input
                                type="password"
                                name="password"
                                class="form-control"
                                required
                                data-minlength="6"
                                id="pwd"
                                placeholder='<?= $view->translate("Password") ?>'
                                data-required-error="<?= $view->translate('Please fill this field') ?>"
                                data-minlength-error="<?= $view->translate('Password length should be >= 6') ?>"
                            >
                            <div class="help-block with-errors"></div>
                        </div>
                        <input type="hidden" name="csrfToken" value="<?= $view->get('session')->getcsrfToken() ?>"
                        <div class="row">
                            <div class="col-md-4"><button type="submit" class="btn btn-primary"><?= $view->translate('Login') ?></button></div>
                            <div class="col-md-4"></div>
                            <div class="col-md-4"><a href="<?= $view->get('router')->getUrlByRouteName('user.register') ?>" class="btn btn-primary"><?= $view->translate('Register') ?></a></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <script>

            $('form').validator()

            function selectLang(sel) {
                window.location.href = "<?= $view->get('router')->getUrlByRouteName('user.login')?>?lang=" + sel.value;
            }

        </script>
    </body>
</html>